// Package grpc - Proto stubs
// This file contains placeholder types for proto-generated code.
// Run `protoc --go_out=. --go-grpc_out=. api/proto/comx.proto` to generate actual types.
package grpc

// Proto message stubs - these would be generated by protoc
// For now, we define them manually to allow compilation

// GetStatusRequest is the request for GetStatus.
type GetStatusRequest struct{}

// StatusResponse is the response for GetStatus.
type StatusResponse struct {
	Running      bool
	GatewayCount int32
	Gateways     map[string]*GatewayStatusProto
}

// GatewayStatusProto is the proto gateway status.
type GatewayStatusProto struct {
	Name             string
	State            ConnectionState
	MessagesSent     uint64
	MessagesReceived uint64
	BytesSent        uint64
	BytesReceived    uint64
	Errors           uint64
}

// ConnectionState represents connection state.
type ConnectionState int32

const (
	ConnectionState_DISCONNECTED ConnectionState = 0
	ConnectionState_CONNECTING   ConnectionState = 1
	ConnectionState_CONNECTED    ConnectionState = 2
	ConnectionState_RECONNECTING ConnectionState = 3
	ConnectionState_ERROR        ConnectionState = 4
)

// ListGatewaysRequest is the request for ListGateways.
type ListGatewaysRequest struct{}

// ListGatewaysResponse is the response for ListGateways.
type ListGatewaysResponse struct {
	Gateways []*GatewayInfo
}

// GetGatewayRequest is the request for GetGateway.
type GetGatewayRequest struct {
	Name string
}

// GatewayInfo is gateway information.
type GatewayInfo struct {
	Name      string
	State     ConnectionState
	Transport *TransportConfig
	Protocol  *ProtocolConfig
}

// TransportConfig is transport configuration.
type TransportConfig struct {
	Type    string
	Address string
	Options map[string]string
}

// ProtocolConfig is protocol configuration.
type ProtocolConfig struct {
	Type    string
	Options map[string]string
}

// AddGatewayRequest is the request for AddGateway.
type AddGatewayRequest struct {
	Name      string
	Transport *TransportConfig
	Protocol  *ProtocolConfig
}

// RemoveGatewayRequest is the request for RemoveGateway.
type RemoveGatewayRequest struct {
	Name string
}

// RemoveGatewayResponse is the response for RemoveGateway.
type RemoveGatewayResponse struct {
	Success bool
}

// SendRequest is the request for Send.
type SendRequest struct {
	Gateway string
	Data    []byte
}

// SendResponse is the response for Send.
type SendResponse struct {
	BytesSent int32
}

// ReceiveRequest is the request for Receive.
type ReceiveRequest struct {
	Gateway   string
	TimeoutMs int32
}

// ReceiveResponse is the response for Receive.
type ReceiveResponse struct {
	Data []byte
}

// ExecuteRequest is the request for Execute.
type ExecuteRequest struct {
	Gateway    string
	Command    string
	Parameters map[string]string
}

// ExecuteResponse is the response for Execute.
type ExecuteResponse struct {
	Success bool
	Data    []byte
	Error   string
}

// SubscribeRequest is the request for Subscribe.
type SubscribeRequest struct {
	Gateway string
}

// Message is a streamed message.
type Message struct {
	Data      []byte
	Timestamp int64
}

// UnimplementedComxServiceServer is for forward compatibility.
type UnimplementedComxServiceServer struct{}

// ComxService_SubscribeServer is the subscribe stream server.
type ComxService_SubscribeServer interface {
	Send(*Message) error
	Context() interface {
		Done() <-chan struct{}
		Err() error
	}
}

// RegisterComxServiceServer registers the service.
func RegisterComxServiceServer(s interface{}, srv interface{}) {
	// This would be implemented by protoc-generated code
}
